Update SoapBase.php
nfephp-org/sped-common pull request #247
Opened 2021-06-30 01:08 UTC by elvispdosreis

Alterar a dependência para o Filesystem 2

2021-07-01 22:55 UTC, olavocneto requested changes
1. De outra revisada onde é usado a propriedade `filesystem` pois acredito que tem mais chamada ao método `has`.
2. O Adpatar no método `setLocalFolder` também precisa ser atualizado para o V2

Abraço!

2021-07-01 22:55 UTC, olavocneto commented on src/Soap/SoapBase.php
> +        $ret &= $this->filesystem->write(
Olá Elvis!! Obrigado pelo PR! Versão 2 do thephpleague/flysystem não retorna mais boleano, leia https://flysystem.thephpleague.com/v2/docs/what-is-new/. Acredito que aqui devemos envolver em um `try catch` e capturar a exceção `FilesystemException`

2021-07-01 22:55 UTC, olavocneto commented on src/Soap/SoapBase.php
>          try {
Capturar exceção `FilesystemException`

2021-07-28 11:46 UTC, robmachado commented
Como dito na ISSUE aberta, estou substituindo o Flysystem com uma classe interna que imita (porcamente) o flysystem.
Como muitos frameworks e aplicações usam diferentes versões do flysystem, não adianta simplesmente mudar de 1 para 2 pois teriam outros impactos.
Por exemplo  o Laravel usa o flysystem na versão 1.* até hoje, e é inviável a convivência de duas versões do mesmo pacote em um mesmo aplicativo.
Estou subindo HOJE essa alteração e isso requer mais testes, portanto se puderem ajudar com os testes agradeço.

2021-07-28 11:53 UTC, closed without merging